### ISSUE TITLE
nrow or row_n

### ISSUE THREAD

**Issue by timelyportfolio** [ayayron/shinydnd#1]
This looks great.  I ran into one problem on the example [lines](https://github.com/ayayron/shinydnd/blame/master/README.md#L82).  Should this be `row_n`?

**Comment by ayayron** [comment]
@timelyportfolio, I've updated the readme to use `row_n` and `col_n`. This will match the syntax for the example in the repository and the syntax for the example at [https://ayayron.shinyapps.io/dragndrop/](https://ayayron.shinyapps.io/dragndrop/).
