### ISSUE TITLE
Using shinydnd with uiOutput and renderUI

### ISSUE THREAD

**Issue by mrhopko** [ayayron/shinydnd#2]
Hi

Thanks for this work - it's marvellous.

I am unable to use the widget from uiOutput. See the example below:

library(shiny)
library(shinyDND)

ui <- shinyUI(
  mainPanel(
    uiOutput("myUI"),
    dragUI("works","works")
    
  )
)

server = shinyServer(function(input, output,session) {
  output$myUI <- renderUI({
    dragUI("doesntwork","doesntwork")
  })
})

# Run the application 
shinyApp(ui = ui, server = server)

**Comment by ayayron** [comment]
@mrhopko there was an issue where the jQuery wasn't getting triggered for new ```renderUI``` elements only the initially created UI elements. This caused both ```dropUI``` and ```dragUI``` elements not to work with ```renderUI```, but now both should work since the jQuery is triggered with newly inserted DOM elements.

**Comment by mrhopko** [comment]
Quick work! The bug appears resolved in the latest version.

**Comment by InitialBD** [comment]
Hi Aaron,
It seems that the version that fixed this bug (allowed draggable UI to be created with renderUI) have a new problem, it progressively slow down when repetitively moving objects. When you move a dragUI several times from one box to another for example, it finally freezes the page. This problem did not occur before for me with the version of ShinyDND available on CRAN (shinyDND_0.1.0 shiny_1.0.5).
Many thanks for your great package.
Bruno

**Comment by vinamra9** [comment]
Hi Ayayron,

Thanks for the update. 
The new version seems to be very slow compared to the previous one. Is there any fix for this problem?

Vinamra
