### ISSUE TITLE
Can I reset the dropUI in server.R?

### ISSUE THREAD

**Issue by cardiomoon** [ayayron/shinydnd#4]
I'd like to choose column names of uploaded data.frame using shinyDND package.

If I upload another data in shiny app, I have to reset the dropUI.  

I can reset the dragSetUI in server.R.

Can I reset the dropUI in server.R?

**Comment by ayayron** [comment]
What do you mean by "reset the dropUI"? I think you just want to move or delete the dragSetUI elements.

**Comment by cardiomoon** [comment]
Yes, I want to delete all elements of dropUI.

**Comment by ayayron** [comment]
The elements in the dropUI are still part of the dragUI or dragSetUI elements, they are not dropUI elements. You would have to delete or hide those elements using something like `.remove()` in jquery (https://api.jquery.com/remove/). There is no function in the package that will delete specific elements.
