### ISSUE TITLE
image disappears when dropped on another image

### ISSUE THREAD

**Issue by jaehyeon-kim** [ayayron/shinydnd#6]
Hi 

I find this package quite handy. When I tried to drag and drop an image onto another, it disappears. After some search, I found a way in a [StackOverflow question](http://stackoverflow.com/questions/29923776/when-i-drag-and-drop-one-image-over-another-why-does-it-disappear).

When I updated the JS code as following, it is no longer a problem.

`  $(".dropelement").on("drop",function(e){
    e.preventDefault();
    var data=e.originalEvent.dataTransfer.getData("Text");
    if (e.target.nodeName !== "IMG") {
      e.target.appendChild(document.getElementById(data));
      var el = $(e.target);
      el.trigger("change");
    }
  });`

Would you consider to update your package?

Regards
Jaehyeon

**Comment by ayayron** [comment]
@jaehyeon-kim, thanks for looking into this. Sure, I can take a look to add this. Do you have a small example app that you've tested it on so I can verify it's working as expected?

**Comment by jaehyeon-kim** [comment]
Please see this sample app - https://github.com/jaehyeon-kim/shiny-dnd-sample.

Images don't disappear if the package is installed from the forked repo - https://github.com/jaehyeon-kim/shinydnd.
